receivers:
  foundationdb:


processors:
  batch:
  resource:
    attributes:
    - key: host.name
      value: localhost
      action: upsert
    - key: service.name
      value: foundationdb 
      action: upsert
    - key: telemetry.sdk.version
      value: 1
      action: upsert
    - key: telemtry.sdk.name
      value: otel-collector
      action: upsert
exporters:
  logging:
# configuring otlp to developer satellites
  otlp:
    endpoint: 172.17.0.1:8360
    tls: 
      insecure: true
service:
  pipelines:
    traces:
      receivers: [foundationdb]
      processors: [batch, resource]
      exporters: [logging, otlp]

